'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { useSelectedLayoutSegment } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, team,dashboard }) {
  const segment = useSelectedLayoutSegment();

  console.log(segment);

  return (
    <html lang="en">
      <body className={inter.className}>
        {children}    
        {segment === "blog" ? team : dashboard}
      </body>
    </html>
  );
}
