'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import { useSelectedLayoutSegment } from "next/navigation";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, team,dashboard }) {
  const segment = useSelectedLayoutSegment();

  console.log(segment);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/">Home</Link>
        <br/>
        <Link href="/blog">Blog</Link>
        {children}    
        {team}
        {dashboard}
      </body>
    </html>
  );
}
