import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Modal from "./ui/modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, auth }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/login">Login</Link>
        <br />
        <Link href="/blog">Blog</Link>
        {auth}
        {children}
        </body>
    </html>
  );
}
